# -------- This file is automatically generated by LSST's sconsUtils -------- #
from typing import Dict, Optional


__version__: str = "unknown"
__repo_version__: str = "unknown"
__fingerprint__: str = "416445cdbf2a1c8f9564380ef7a00d9edcc82072 *"
__dependency_versions__: Dict[str, Optional[str]] = {}
__all__ = (
    "__version__",
    "__repo_version__",
    "__fingerprint__",
    "__dependency_versions__",
)
