# -------- This file is automatically generated by LSST's sconsUtils -------- #
from typing import Dict, Optional


__version__: str = "unknown"
__repo_version__: str = "unknown"
__fingerprint__: str = "0c4b2a94af11490b8683170fb2c2f7fb48b027b0 *"
__dependency_versions__: Dict[str, Optional[str]] = {}
__all__ = (
    "__version__",
    "__repo_version__",
    "__fingerprint__",
    "__dependency_versions__",
)
