# -------- This file is automatically generated by LSST's sconsUtils -------- #
from typing import Dict, Optional


__version__: str = "unknown"
__repo_version__: str = "unknown"
__fingerprint__: str = "0677581c5b5b6b10ef83c45f6e9c301b281cec28 *"
__dependency_versions__: Dict[str, Optional[str]] = {}
__all__ = (
    "__version__",
    "__repo_version__",
    "__fingerprint__",
    "__dependency_versions__",
)
